//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAD_HoangThaiSon_C2009L.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmpID { get; set; }

        [Required(ErrorMessage = "You must enter the name and it's required")]
        [Display(Name = "Employee Name")]
        [StringLength(32, MinimumLength = 3, ErrorMessage = "Employee name length must be between 3 and 32")]
        public string EmpName { get; set; }

        [Required(ErrorMessage = "Quantity mustn't be empty")]
        [Range(0, 999999, ErrorMessage = "Quantity is not negative and have maximum 999999 unit")]
        public int DeptID { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Address { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "The email is required")]
        [EmailAddress(ErrorMessage = "You must enter a valid email")]
        public string Email { get; set; }

        [Required(ErrorMessage ="This field is required")]
        [Display(Name = "DOJ")]
        public string DOJ { get; set; }

        [Required(ErrorMessage = "The gender is missing and Gender must be male of female")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "This is required")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}"
            , ApplyFormatInEditMode = true)]
        public System.DateTime YearOfBirth { get; set; }

        public virtual Department Department { get; set; }
    }
}
