//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAD_C2009L_HoangThaiSon1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int ProductId { get; set; }
        [Required(ErrorMessage = "You must enter the name and it's required")]
        [Display(Name = "Product Name")]
        [StringLength(32, MinimumLength = 3, ErrorMessage = "Product name length must be between 3 and 32")]
        public string ProductName { get; set; }
        [Required(ErrorMessage ="Price mustn't be empty")]
        [RegularExpression(@"^\d+.?\d{0,4}$", ErrorMessage = "Invalid Price - must be decimal number; Maximum Four Decimal Points. VD: 99.9999")]
        [Range(-9999999999999999.9999, 9999999999999999.9999)]
        public Nullable<decimal> Price { get; set; }
        [Required(ErrorMessage = "Quantity mustn't be empty")]
        [Range(0,999999,ErrorMessage ="Quantity is not negative and have maximum 999999 unit")]
        public Nullable<int> Quantity { get; set; }
        [Required(ErrorMessage = "Release Date mustn't be empty")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public int CategoryId { get; set; }
        public virtual Category Category { get; set; }
    }
}
